name: Production Deployment - Docs
on:
  push:
    branches:
      - main
    paths:
      - apps/docs/**
      - packages/**
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build --filter=docs